/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.forms;
import gestion.dao.CommandeAchatDAOImpl;
import gestion.dao.FournisseurDAOImpl;
import gestion.dao.ProduitDAOImpl;
import gestion.model.CommandeAchat;
import gestion.model.Fournisseur;
import gestion.model.Produit;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class CommandeFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CommandeFrame
     */
    private CommandeAchatDAOImpl commandeDAO = new CommandeAchatDAOImpl();
    private FournisseurDAOImpl fournisseurDAO = new FournisseurDAOImpl();
    private ProduitDAOImpl produitDAO = new ProduitDAOImpl();

    public CommandeFrame() {
        initComponents();
        chargerComboFournisseur();
        chargerComboProduit();
        chargerTable();
    this.setSize(800, 600);
    this.setResizable(true);
    this.setMaximizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbFournisseur = new javax.swing.JComboBox();
        cmbProduit = new javax.swing.JComboBox();
        cmbStatut = new javax.swing.JComboBox();
        txtQuantite = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnVider = new javax.swing.JButton();
        btnLivrer = new javax.swing.JButton();
        dateCommande = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(33, 97, 140));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Commandes ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jTable1.setBackground(new java.awt.Color(33, 97, 140));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_commande", "fournisseur", "produit", "date", "quantite", "statut"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(450, 300));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(33, 97, 140));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(509, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fournisseur :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produit :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantité :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Statut :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        cmbFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFournisseurActionPerformed(evt);
            }
        });
        jPanel1.add(cmbFournisseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, -1));

        cmbProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProduitActionPerformed(evt);
            }
        });
        jPanel1.add(cmbProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, -1));

        cmbStatut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En cours", "Livrée", " " }));
        cmbStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatutActionPerformed(evt);
            }
        });
        jPanel1.add(cmbStatut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, -1));
        jPanel1.add(txtQuantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        jPanel1.add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 110, -1));

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        jPanel1.add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 110, -1));

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 110, -1));

        btnVider.setText("Vider");
        btnVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderActionPerformed(evt);
            }
        });
        jPanel1.add(btnVider, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, -1));

        btnLivrer.setText("Valider Livraison");
        btnLivrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrerActionPerformed(evt);
            }
        });
        jPanel1.add(btnLivrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));
        jPanel1.add(dateCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void chargerComboFournisseur() {
    cmbFournisseur.removeAllItems();
    List<Fournisseur> liste = fournisseurDAO.findAll();
    for (Fournisseur f : liste) {
        cmbFournisseur.addItem(f);
    }
}

private void chargerComboProduit() {
    cmbProduit.removeAllItems();
    List<Produit> liste = produitDAO.findAll();
    for (Produit p : liste) {
        cmbProduit.addItem(p);
    }
}

private void chargerTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    List<CommandeAchat> liste = commandeDAO.findAll();
    for (CommandeAchat c : liste) {
        model.addRow(new Object[]{
            c.getIdCommande(),
            c.getFournisseur().getNom(),
            c.getProduit().getLibelle(),
            c.getDateCommande(),
            c.getQuantite(),
            c.getStatut()
        });
    }
}

private void viderChamps() {
    cmbFournisseur.setSelectedIndex(0);
    cmbProduit.setSelectedIndex(0);
    dateCommande.setDate(null);
    txtQuantite.setText("");
    cmbStatut.setSelectedIndex(0);
}
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        
        Fournisseur fournisseur = (Fournisseur) cmbFournisseur.getSelectedItem();
Produit produit = (Produit) cmbProduit.getSelectedItem();
String quantiteStr = txtQuantite.getText().trim();
java.util.Date date = dateCommande.getDate();
String statut = cmbStatut.getSelectedItem().toString();

if (fournisseur == null || produit == null || date == null || quantiteStr.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Veuillez remplir tous les champs !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    int quantite = Integer.parseInt(quantiteStr);
    if (quantite <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "La quantité doit être supérieure à 0 !",
            "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    CommandeAchat c = new CommandeAchat(fournisseur, produit, date, quantite, statut);
    commandeDAO.create(c);
    chargerTable();
    viderChamps();
    javax.swing.JOptionPane.showMessageDialog(this,
        "Commande ajoutée avec succès !",
        "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "La quantité doit être un nombre !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void cmbFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFournisseurActionPerformed

    private void cmbStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatutActionPerformed

    private void cmbProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProduitActionPerformed

    private void btnViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderActionPerformed
        // TODO add your handling code here:
        viderChamps();
    }//GEN-LAST:event_btnViderActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner une commande !",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String statut = jTable1.getValueAt(row, 5).toString();
        if (statut.equals("Livrée")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Impossible de modifier une commande déjà livrée !",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Fournisseur fournisseur = (Fournisseur) cmbFournisseur.getSelectedItem();
        Produit produit = (Produit) cmbProduit.getSelectedItem();
        String quantiteStr = txtQuantite.getText().trim();
        java.util.Date date = dateCommande.getDate();
        String statutNew = cmbStatut.getSelectedItem().toString();

        try {
            int quantite = Integer.parseInt(quantiteStr);
            int id = (int) jTable1.getValueAt(row, 0);
            CommandeAchat c = new CommandeAchat(id, fournisseur, produit, date, quantite, statutNew);
            commandeDAO.update(c);
            chargerTable();
            viderChamps();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Commande modifiée avec succès !",
                "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La quantité doit être un nombre !",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner une commande !",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String statut = jTable1.getValueAt(row, 5).toString();
        if (statut.equals("Livrée")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Impossible de supprimer une commande déjà livrée !",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Voulez-vous vraiment supprimer cette commande ?",
            "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            int id = (int) jTable1.getValueAt(row, 0);
            commandeDAO.delete(id);
            chargerTable();
            viderChamps();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Commande supprimée avec succès !",
                "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnLivrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrerActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner une commande !",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String statut = jTable1.getValueAt(row, 5).toString();
        if (statut.equals("Livrée")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Cette commande est déjà livrée !",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Confirmer la livraison ? Le stock sera mis à jour automatiquement.",
            "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            int id = (int) jTable1.getValueAt(row, 0);
            commandeDAO.validerLivraison(id);
            chargerTable();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Livraison validée ! Stock mis à jour !",
                "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLivrerActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            txtQuantite.setText(jTable1.getValueAt(row, 4).toString());
            cmbStatut.setSelectedItem(jTable1.getValueAt(row, 5).toString());
            if (jTable1.getValueAt(row, 3) != null) {
                dateCommande.setDate((java.util.Date) jTable1.getValueAt(row, 3));
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnLivrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnVider;
    private javax.swing.JComboBox cmbFournisseur;
    private javax.swing.JComboBox cmbProduit;
    private javax.swing.JComboBox cmbStatut;
    private com.toedter.calendar.JDateChooser dateCommande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtQuantite;
    // End of variables declaration//GEN-END:variables

    
}
