/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.forms;
import gestion.dao.CommandeAchatDAOImpl;
import gestion.dao.FournisseurDAOImpl;
import gestion.model.CommandeAchat;
import gestion.model.Fournisseur;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FiltreFournisseurFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiltreFournisseurFrame
     */
    private CommandeAchatDAOImpl commandeDAO = new CommandeAchatDAOImpl();
private FournisseurDAOImpl fournisseurDAO = new FournisseurDAOImpl();
    public FiltreFournisseurFrame() {
        initComponents();
        chargerComboFournisseur();
    this.setSize(700, 500);
    this.setResizable(true);
    this.setMaximizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResultat = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbFournisseur = new javax.swing.JComboBox();
        btnRechercher = new javax.swing.JButton();
        btnReinitialiser = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(33, 97, 140));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Résultats", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(446, 300));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(440, 280));

        tableResultat.setBackground(new java.awt.Color(33, 97, 140));
        tableResultat.setForeground(new java.awt.Color(255, 255, 255));
        tableResultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_commande", "fournisseur", "produit", "date", "quantite", "statut"
            }
        ));
        tableResultat.setPreferredSize(new java.awt.Dimension(450, 350));
        jScrollPane1.setViewportView(tableResultat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(33, 97, 140));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fournisseur :");

        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        btnReinitialiser.setText("Réinitialiser");
        btnReinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinitialiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRechercher)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnReinitialiser))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cmbFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRechercher)
                    .addComponent(btnReinitialiser))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        // TODO add your handling code here:
        
        Fournisseur fournisseur = (Fournisseur) cmbFournisseur.getSelectedItem();
if (fournisseur == null) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Veuillez sélectionner un fournisseur !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}
List<CommandeAchat> liste = commandeDAO.findByFournisseur(fournisseur.getIdFournisseur());
afficherResultats(liste);
if (liste.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Aucune commande trouvée pour ce fournisseur !",
        "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinitialiserActionPerformed
        // TODO add your handling code here:
        
        cmbFournisseur.setSelectedIndex(0);
    DefaultTableModel model = (DefaultTableModel) tableResultat.getModel();
    model.setRowCount(0);
    }//GEN-LAST:event_btnReinitialiserActionPerformed

    private void chargerComboFournisseur() {
    cmbFournisseur.removeAllItems();
    List<Fournisseur> liste = fournisseurDAO.findAll();
    for (Fournisseur f : liste) {
        cmbFournisseur.addItem(f);
    }
}

private void afficherResultats(List<CommandeAchat> liste) {
    DefaultTableModel model = (DefaultTableModel) tableResultat.getModel();
    model.setRowCount(0);
    for (CommandeAchat c : liste) {
        model.addRow(new Object[]{
            c.getIdCommande(),
            c.getFournisseur().getNom(),
            c.getProduit().getLibelle(),
            c.getDateCommande(),
            c.getQuantite(),
            c.getStatut()
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton btnReinitialiser;
    private javax.swing.JComboBox cmbFournisseur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableResultat;
    // End of variables declaration//GEN-END:variables

    
}
