/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.forms;
import gestion.dao.ProduitDAOImpl;
import gestion.model.Produit;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ProduitFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProduitFrame
     */
    private ProduitDAOImpl dao = new ProduitDAOImpl();
    public ProduitFrame() {
        initComponents();
        chargerTable();
    this.setSize(800, 600);
    this.setResizable(true);
    this.setMaximizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        txtCategorie = new javax.swing.JTextField();
        txtPrixAchat = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnVider = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(33, 97, 140));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Libellé :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Catégorie :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prix Achat :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stock :");

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnVider.setText("Vider");
        btnVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtPrixAchat)
                    .addComponent(txtStock)
                    .addComponent(txtLibelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSupprimer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVider))
                .addGap(316, 316, 316))
        );

        jPanel2.setBackground(new java.awt.Color(33, 97, 140));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Produits", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jTable1.setBackground(new java.awt.Color(33, 97, 140));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_produit", "libelle", "categorie", "prixAchat", "stock"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void chargerTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    List<Produit> liste = dao.findAll();
    for (Produit p : liste) {
        model.addRow(new Object[]{
            p.getIdProduit(),
            p.getLibelle(),
            p.getCategorie(),
            p.getPrixAchat(),
            p.getStock()
        });
    }
}

    private void viderChamps() {
    txtLibelle.setText("");
    txtCategorie.setText("");
    txtPrixAchat.setText("");
    txtStock.setText("");
}
    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
       // TODO add your handling code here:
        
        String libelle = txtLibelle.getText().trim();
String categorie = txtCategorie.getText().trim();
String prixStr = txtPrixAchat.getText().trim();
String stockStr = txtStock.getText().trim();

if (libelle.isEmpty() || categorie.isEmpty() || prixStr.isEmpty() || stockStr.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Veuillez remplir tous les champs !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    double prix = Double.parseDouble(prixStr);
    int stock = Integer.parseInt(stockStr);
    
    if (prix <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Le prix doit être supérieur à 0 !",
            "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (stock < 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Le stock ne peut pas être négatif !",
            "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Produit p = new Produit(libelle, categorie, prix, stock);
    dao.create(p);
    chargerTable();
    viderChamps();
    javax.swing.JOptionPane.showMessageDialog(this,
        "Produit ajouté avec succès !",
        "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Prix et Stock doivent être des nombres !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
if (row == -1) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Veuillez sélectionner un produit !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

String libelle = txtLibelle.getText().trim();
String categorie = txtCategorie.getText().trim();
String prixStr = txtPrixAchat.getText().trim();
String stockStr = txtStock.getText().trim();

if (libelle.isEmpty() || categorie.isEmpty() || prixStr.isEmpty() || stockStr.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Veuillez remplir tous les champs !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    double prix = Double.parseDouble(prixStr);
    int stock = Integer.parseInt(stockStr);
    int id = (int) jTable1.getValueAt(row, 0);
    
    Produit p = new Produit(id, libelle, categorie, prix, stock);
    dao.update(p);
    chargerTable();
    viderChamps();
    javax.swing.JOptionPane.showMessageDialog(this,
        "Produit modifié avec succès !",
        "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Prix et Stock doivent être des nombres !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
if (row == -1) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Veuillez sélectionner un produit !",
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

String libelle = jTable1.getValueAt(row, 1).toString();
int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
    "Voulez-vous vraiment supprimer " + libelle + " ?",
    "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);

if (confirm == javax.swing.JOptionPane.YES_OPTION) {
    int id = (int) jTable1.getValueAt(row, 0);
    dao.delete(id);
    chargerTable();
    viderChamps();
    javax.swing.JOptionPane.showMessageDialog(this,
        "Produit supprimé avec succès !",
        "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderActionPerformed
        // TODO add your handling code here:
        viderChamps();
    }//GEN-LAST:event_btnViderActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
if (row != -1) {
    txtLibelle.setText(jTable1.getValueAt(row, 1).toString());
    txtCategorie.setText(jTable1.getValueAt(row, 2).toString());
    txtPrixAchat.setText(jTable1.getValueAt(row, 3).toString());
    txtStock.setText(jTable1.getValueAt(row, 4).toString());
}
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnVider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCategorie;
    private javax.swing.JTextField txtLibelle;
    private javax.swing.JTextField txtPrixAchat;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    
}
